### ISSUE TITLE
Crash when filteredOrderDictionarysUsingPredicateForObjects

### ISSUE THREAD

**Issue by dsdjung** [Marxon13/M13OrderedDictionary#23]
Function fails at initwithobjects during assert on count check.
j++ within if check should not be there?

- (M13OrderedDictionary *)filteredOrderDictionarysUsingPredicateForObjects:(NSPredicate *)predicate
{
    NSArray *tempObj = [objects filteredArrayUsingPredicate:predicate];
    int i = 0;
    int j = 0;
    NSMutableArray *tempKey = [[NSMutableArray alloc] init];
    //Iterate though, since all objects are returned in order, you can just look along, object by object, untill they are equal, and grab the coresponding key.
    while (i < tempObj.count && j < keys.count) {
        if ([[tempObj objectAtIndex:i] isEqual:[objects objectAtIndex:j]]) {
            [tempKey addObject:[keys objectAtIndex:j]];
//            j++;
            i++;
        }
        j++;
    }
    return [[M13OrderedDictionary alloc] initWithObjects:tempObj pairedWithKeys:tempKey];
}

**Comment by michaelforrest** [comment]
+1 I just discovered this bug too - the j++ at https://github.com/Marxon13/M13OrderedDictionary/blob/master/M13OrderedDictionary.m#L517 needs to be removed
